export default {
  // CHANGE_TAB,
  // FETCH_CURRENT_WORKOUT,
  // FETCH_CURRENT_WORKOUT_COMPLETE,
  // SET_EXERCISE_VISIBILITY,
  // ADD_EXERCISE,
  // ADD_EXERCISE_COMPLETE,
  TOGGLE_MODAL: "TOGGLE_MODAL"
};
